name: Deploy to Vertex AI

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger on

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Modify the model
      run: |
        python model.py
    
    - name: Build Docker image
      run: |
        gcloud auth configure-docker asia-south2-docker.pkg.dev
        docker build -t asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/model-server/img:latest .
        docker push asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/model-server/img:latest

    - name: Upload model to GCS
      run: |
        gsutil cp random_forest_model.pkl gs://$GCS_BUCKET_NAME/random_forest_model.pkl

    - name: Install dependencies
      run: pip install google-cloud-aiplatform

    - name: Deploy to Vertex AI
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      run: python deploy_to_vertex.py
